_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
            "3":
                - 2
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.7
            "6": 4.49.0
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": darwin-arm64
